version: "3"

services:
  invoice:
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USERNAME=postgres_test
      - POSTGRES_PASSWORD=postgres_test123
      - POSTGRES_DB=postgres_test
